module.exports = [
  "hai!",
  "hiyah!",
  "HYAHHH!",
  "Hey! Listen!",
  "Great Deku Tree",
  "Hyrule",
  "Master Sword",
  "Navi",
  "ocarina",
  "sages",
  "evil realm",
  "five temples",
  "sacred realm",
  "door of time",
  "Epona",
  "Link",
  "Zelda",
  "Sheik",
  "Kakariko village",
  "Death Mountain",
  "Hero of Time",
  "house of the dead",
  "forest temple",
  "fire temple",
  "water temple",
  "shadow temple",
  "spirit temple",
  "hero's bow",
  "Temple of Time",
  "Triforce",
  "evil laugh",
  "light arrows",
  "CURSE YOU, LINK",
  "Triforce of Power",
  "Triforce of Wisdom",
  "Triforce of Courage",
  "Mido",
  "Kokiri sword",
  "Deku shield",
  "Deku nut",
  "fishing rod",
  "slingshot",
  "Saria",
  "fairy",
  "sacred forest meadow",
  "Malon",
  "milk bottle",
  "SUPER CUCCOOS",
  "Nabooru",
  "desert fortress",
  "Gerudo",
  "silver gauntlets",
  "Princess Ruto",
  "Jabu-Jabu",
  "electrified jellyfish",
  "Zora's domain",
  "Zora's sapphire",
  "chamber of sages",
  "boy without a fairy",
  "Hylian",
  "Kaepora Gabora",
  "hoo hoo ho",
  "mysterious power",
  "Lon Lon Ranch",
  "Hyrule Castle",
  "sunken temple",
  "Great Fairy",
  "Biggoron's sword",
  "Medigoron",
  "postman",
  "Cuccoo lady",
  "pocket cuccoo",
  "treasure chest",
  "compass",
  "dungeon map",
  "spin attack",
  "gossip stone",
  "golden skulltula",
  "Dodongo's cavern",
  "Kokiri emerald",
  "Goron's ruby",
  "sworn brother",
  "spiritual stones",
  "redead",
  "Poe",
  "Deku Tree sprout",
  "sun song",
  "song of storms",
  "cow",
  "running man",
  "windmill man",
  "Deku scrub",
  "power of the gods",
  "the chosen one",
  "chosen by the gods",
  "pedestal of time",
  "legend",
  "ancient melody",
  "Goron hug",
  "Bombchu",
  "odd mushroom",
  "lost woods",
  "bunny hood",
  "eyeball frog",
  "giant's knife",
  "keaton mask",
  "skull mask",
  "mask of truth",
  "hookshot",
  "boomerang",
  "iron boots",
  "Deku stick",
  "lens of truth",
  "ocarina of time",
  "Farore's wind",
  "Nayru's love",
  "Din's fire",
  "blue potion",
  "red potion",
  "green potion",
  "magic bean",
  "mirror shield",
  "hover boots",
  "blue fire",
  "rupee",
  "castle town",
  "boss key",
  "piece of heart",
  "huh?",
  "magic meter",
  "ghost shop",
  "Poe in a bottle",
  "z-targeting",
  "tektite",
  "big poe",
  "deku baba",
  "keese",
  "gibdo",
  "floormaster",
  "Gohma",
  "iron knuckle",
  "Like-Like",
  "octorok",
  "peahat",
  "stalfos",
  "wallmaster",
  "wolfos",
  "flying pot",
  "dark Link",
  "phantom Ganon",
  "twinrova",
  "Bongo Bongo",
  "Pierre",
  "happy mask salesman",
  "Hyrule field",
  "bottom of the well",
  "desert colossus"
]
